name: prepare
on: push
  
jobs:
  prepare:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd 2022
          .\Convert-InputToPython.ps1
        shell: powershell
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: always()
        with:
          commit_message: Auto-committing results
          commit_options: '--no-verify --signoff'
          file_pattern: 2022/*.*
          add_options: '-A'
          skip_fetch: true
