name: solve
on:
  workflow_dispatch:

jobs:
  solve:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          .\Runner\Invoke-Solution.ps1
        shell: powershell
